#!/usr/bin/env sh

cd /
apt-get update
apt-get --yes install git
git clone https://github.com/omninet-node/omninet-infra--composer.git www
apt-get remove docker docker-engine docker.io containerd runc;
apt-get update;
apt-get --yes install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common;
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -;
apt-key fingerprint 0EBFCD88;
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable";
apt-get update;
apt-get --yes install docker-ce docker-ce-cli containerd.io docker-compose;
apt-get --yes install gnupg2 pass;
gpg2 -k;
pass init "docker";
systemctl enable docker;
systemctl start docker;
chmod -R 0777 /www/apps;
chmod -R 0777 /www/static;
docker login -ullevkin --password-stdin;
cd /www;
docker-compose -f prod.yml up -d;
